### ISSUE TITLE
SmppSessionsImpl.fireUnknownThrowable() - NullPointerException

### ISSUE THREAD

**Issue by vetss** [RestComm/jain-slee.smpp#3]
2017-02-14 14:14:34,557 WARNING [org.jboss.netty.channel.DefaultChannelPipeline] (ots.dc) An exception was thrown by a user handler while handling an exception event ([id: 0x52048287, /172.25.10.172:42584 => smpp3.infobip.com/193.105.74.58:8888] EXCEPTION: java.io.IOException: Connection reset by peer)
java.lang.NullPointerException
       	at org.restcomm.slee.resource.smpp.SmppSessionsImpl$SmppSessionHandlerImpl.fireUnknownThrowable(SmppSessionsImpl.java:480)
       	at org.restcomm.smpp.SmppClientOpsThread$ClientSmppSessionHandler.fireUnknownThrowable(SmppClientOpsThread.java:372)
       	at com.cloudhopper.smpp.impl.DefaultSmppSession.fireExceptionThrown(DefaultSmppSession.java:673)
       	at com.cloudhopper.smpp.channel.SmppSessionWrapper.exceptionCaught(SmppSessionWrapper.java:62)
       	at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
       	at com.cloudhopper.smpp.channel.SmppSessionLogger.handleUpstream(SmppSessionLogger.java:104)
       	at com.cloudhopper.smpp.channel.SmppSessionThreadRenamer.handleUpstream(SmppSessionThreadRenamer.java:59)
       	at com.cloudhopper.smpp.channel.SmppClientConnector.exceptionCaught(SmppClientConnector.java:75)
       	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
       	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:74)
       	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
       	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
       	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       	at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/jain-slee.smpp/commit/fd201c2c58b603345d1d4c800723f675d1e3a602
